steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - proxy
      - --region=us-east4
      - --source=.
      - --trigger-http
      - --runtime=python311
