steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "--upgrade", "pip", "--user"]
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - proxy
      - --region=us-east4
      - --source=.
      - --set-env-vars
      - PROJECT_ID=development-380917
      - --trigger-http
      - --entry-point=proxy
      - --runtime=python311
      - --allow-unauthenticated
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - new_user
      - --region=us-east4
      - --source=.
      - --set-env-vars
      - PROJECT_ID=development-380917,TOPIC_ID=new_user
      - --trigger-topic=new_user
      - --entry-point=new_user
      - --runtime=python311
      - --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY
