
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Amichay Oren", email = "amichay@nine30.com"},
]
dependencies = [
    "openapi>=1.1.0",
    "functions-framework>=3.4.0",
    "requests>=2.31.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}
