
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Amichay Oren", email = "amichay@nine30.com"},
]
dependencies = [
    "google-cloud-firestore>=2.11.1",
]
requires-python = ">=3.11"
license = {text = "MIT"}
