name: "Cloud-Functions-Infrastructure"

on:
  push:
    branches: ["master"]

  workflow_dispatch:
    branches: ["master"]

permissions:
  contents: read

jobs:
  files-changed:
    name: Infra
    runs-on: ubuntu-20.04
    timeout-minutes: 3

    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            infra:
              - 'infra/**'

      # run only if some file in 'infra' folder was changed
      - if: steps.changes.outputs.infra == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - if: steps.changes.outputs.infra == 'true' 
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -
          cd infra
          pdm build

