name: "Cloud-Functions-Infrastructure"

on:
  push:
    branches: ["master"]

  workflow_dispatch:
    branches: ["master"]

permissions:
  contents: read

jobs:
  files-changed:
    name: Infra
    runs-on: ubuntu-20.04
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: lostick/path-filtering-action@main
      - name: setup go
        if: env.DIFF_DETECTED == 'true'
        uses: actions/setup-go@v2
