name: "Cloud-Functions-Infrastructure"

on:
  push:
    branches: ["master"]

  workflow_dispatch:
    branches: ["master"]

permissions:
  contents: read

jobs:
  files-changed:
    name: Infra
    runs-on: ubuntu-20.04
    timeout-minutes: 3

  steps:
    - name: Check Changes in Infra
      uses: dorny/paths-filter@v2.2.1
      id: changes
      with:
        filters: |
          src:
            - 'infra/**'

    # run only if some file in 'src' folder was changed
    - name: deploy package if changed
      if: steps.changes.outputs.src == 'true'
      run: hello
